title: Oriana Turus
description: Autrice | Author
url: "https://orianawrites.eu"
permalink: /:year/:month/:day/:title/

author:
  name: Oriana Turus
  substack: "https://ballafirmatario0u.substack.com/"
  email: ""

social:
  - title: linkedin
    url: https://www.linkedin.com/in/oriana-turus-31197549/
  - title: twitter
    url: https://twitter.com/ori_tur81
  - title: facebook
    url: https://www.facebook.com/ilfilodioriana
  - title: instagram
    url: https://www.instagram.com/oriana_turus_autrice/

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
